{% set name = "logilab-common" %}
{% set version = "1.5.0" %}
{% set sha256 = "2d1182dbeef3033e63a84e737509ec190e3dac977b2d7c16d8e6c8022444ab71" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - logilab
    - logilab.common
    - logilab.common.ureports

about:
  home: http://www.logilab.org/project/logilab-common
  license: LGPL 2.1
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: 'collection of low-level Python packages and modules used by Logilab projects'

extra:
  recipe-maintainers:
    - jakirkham
