{% set name = "logilab-common" %}
{% set version = "1.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logilab-common-{{ version }}.tar.gz
  sha256: ac08bd39f76b8e4834a2c2d32919472297550f12da59eed332124a74dfb0a40b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mypy_extensions
    - setuptools
    - typing_extensions

test:
  imports:
    - logilab
    - logilab.common
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.logilab.org/project/logilab-common
  summary: collection of low-level Python packages and modules used by Logilab projects
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - jakirkham
